---
antora:
  name: modules
  dir: www
  modules:
    - name: "01-introduction"
      label: "Introduction"
      solveButton: true
    - name: "02-create-container-repository"
      label: "Create Container Repository"
      solveButton: true
    - name: "03-create-activation-key"
      label: "Create Activation Key"
      solveButton: true
    - name: "04-register-image-mode-host"
      label: "Register Image Mode Host"
      solveButton: true
    - name: "05-verify-image-mode-host-details"
      label: "Verify Image Mode Host Details"
      solveButton: true
    - name: "06-update-container-image"
      label: "Update Container Image"
      solveButton: true
    - name: "07-push-container-image"
      label: "Push Container Image"
      solveButton: true
    - name: "08-obtain-container-image-label"
      label: "Obtain Container Image Label"
      solveButton: true
    - name: "09-schedule-remote-job"
      label: "Schedule Remote Job"
      solveButton: true

tabs:
  - name: "Satellite Web UI"
    url: https://satellite-${guid}.${domain}/
  - name: "satellite.lab terminal"
    url: /wetty_satellite/ssh/root
  - name: "rhel1.lab terminal"
    url: /wetty_rhel1/ssh/root
  - name: "rhel2.lab terminal"
    url: /wetty_rhel2/ssh/root
